### ISSUE TITLE
Wealth Distribution API

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#106]
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/5e8ee7a5-e2f3-493c-a5cf-def8a9c86a77)
Wealth Distribution
0-100
100-500
500-2000
2000-5000
5000-10000
10000-20000
20000-50000
50000-100000
100000-500000
500000+

Number of accounts (y), count of addresses that have range of tokens above (x)

**Comment by iljagrabar14** [comment]
1. select * from spacebox.account_balance ab   (uatom only)
2. select * from spacebox.delegation d 
3. select * from spacebox.unbonding_delegation where time > now()

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 @bro-n-bro-2 please check and close if everything is fine
