### ISSUE TITLE
Total number of delegators historical

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#107]
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/ad72a3a1-2e41-4cf5-9149-f4e9b6339c29)
To create this graph we will require total number delegators historical data
The same structure as total number of accounts ( /statistics/get_statistics_total_accounts)

**Comment by bro-n-bro-0** [comment]
That is too complex right now to implement that issue @bro-n-bro-2
