### ISSUE TITLE
Governance votes

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#108]
Amount of unique accounts participating in the proposal + tally results

![telegram-cloud-photo-size-2-5312467356938783495-y](https://github.com/bro-n-bro/spacebox-api/assets/89854952/2d6f9193-bbde-4f79-acd3-6c11b9b456ee)

**Comment by bro-n-bro-0** [comment]
@bro-n-bro-2 
check that one
/gov/votes

**Comment by bro-n-bro-2** [comment]
Can we add to this endpoint proposal status and voting_end_time ? @bro-n-bro-0

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 added, check and close if everything is ok please

**Comment by bro-n-bro-2** [comment]
Looks good. Thanks
