### ISSUE TITLE
Validator group map

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#110]
1.
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/9ec70900-63c6-4f5f-a39d-5f48add91364)
Delegators/Voting power
Moniker/logo/num of delegators/voting power.

2.
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/4ec1835e-3281-4a49-859d-7d73ede51d0d)
Moniker/logo/num of delegators/commission.

3.
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/9c11fbe9-3f94-4c54-81d6-ff722685596f)
Moniker/logo/commission/voting power

**Comment by iljagrabar14** [comment]
1. Voting power % for all delegator and count of delegations from delegation table for all validators

**Comment by iljagrabar14** [comment]
2. Actual from validator_commission

**Comment by bro-n-bro-0** [comment]
@bro-n-bro-2 
which fields are requested?

**Comment by bro-n-bro-2** [comment]
Moniker/logo_url/operator_address/num of delegators/voting power
Moniker/logo_url/operator_address/num of delegators/commission
Moniker/logo_url/operator_address/commission/voting power

If I understand your question correct.

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 please check api
statistics/validators/group_map
if everything is ok, please close issue

**Comment by bro-n-bro-2** [comment]
@iljagrabar14 , my mistake. Could you please show only validators in active set ?

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 , already implemented, if you see voting power 0, the issue is in indexer (something with pagination), discissed before

**Comment by bro-n-bro-2** [comment]
@prevetal , you can proceed further.
