### ISSUE TITLE
Inactive accounts are broken after Dec 16

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#155]
<img width="830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a10b9be05e8a0db778918e5b1b49505c758ac80/image.png" alt="image.png" />

**Comment by iljagrabar14** [comment]
looks like issue is in view, it's generating data only until now() (now is the moment at which we execute creating of view).

**Comment by iljagrabar14** [comment]
remove dates generation in view

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 fixed, check and close please if everything is ok
