### ISSUE TITLE
Monitoring API Network

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#58]
Network:
Atom Price
Circulating supply 
APR
APY
Inflation
Total Supply
Total Amount of Unbonded Atom
Pending proposals
Active proposals
Total amount of Bonded Atom
Community pool
Last Block Height
Current block time

Params from LCD:

Active validators
Unbound period

Voting period
Min Deposit
Max Deposit Period
Quorum
Threshold
Veto Threshold
Community tax

Signed Blocks Window
Min Signed per Block
Downtime Jail Duration
Slash Fraction Double Sign
Slash Fraction Downtime

**Comment by bro-n-bro-0** [comment]
Network:
- [ ] Atom Price
- [ ] Circulating supply
- [ ] APR
- [ ] APY
- [ ] Inflation
- [ ] Total Supply
- [ ] Total Amount of Unbonded Atom
- [ ] Pending proposals
- [ ] Active proposals
- [ ] Total amount of Bonded Atom
- [ ] Community pool
- [ ] Last Block Height
- [ ] Current block time
- [ ] Active validators
- [ ] Unbound period
- [ ] Voting period
- [ ] Min Deposit
- [ ] Max Deposit Period
- [ ] Quorum
- [ ] Threshold
- [ ] Veto Threshold
- [ ] Community tax
- [ ] Signed Blocks Window
- [ ] Min Signed per Block
- [ ] Downtime Jail Duration
- [ ] Slash Fraction Double Sign
- [ ] Slash Fraction Downtime

**Comment by iljagrabar14** [comment]
3 API for each params (staking, mint, distrubution)

https://lcd.cosmoshub-4.bronbro.io/cosmos/slashing/v1beta1/params
4th api for slash params
