### ISSUE TITLE
Monitoring API Accounts

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#59]
Total accounts
Active accounts
New accounts
Inactive accounts
Active Restake Users
Restake enabled count
Restake token Amount
Gas Paid
Fees Paid
Total amount of transactions

Top transactions per 30 days
Rich list (address, token amount, liquid tokens, staked tokens, Validator, Unbound tokens)
Whale transactions (account, action, amount, to address, TX link)
Governance participation (№ proposal, account number votes, account token amount, validator amount votes, validator token amount, proposal status, Vote ration (account number votes/validator amount votes))
Unbound/stake/redelegations
Amount of unique accounts participating in proposal, excluding accounts with < 0.01 Atom
Average stake (amount of accounts with less than 1k, 1k-5k, 5k-10k, > 10k)

Investigate:
Vesting accounts

**Comment by Zoltan118** [comment]
Will whale transactions include IBC transactions too? or only Cosmos to Cosmos / Osmosis to Osmosis txs etc. ?

**Comment by iljagrabar14** [comment]
detailing: hours, days, week, month

**Comment by iljagrabar14** [comment]
history data: 
Active accounts
New accounts
Gas Paid (from block table)
Total amount of transactions

one value:
Total accounts
Top transactions per 30 days - message JOIN transaction JOIN block filter 30 days, group by type
Average stake (amount of accounts with less than 1k, 1k-5k, 5k-10k, > 10k)

Inactive accounts - last transaction > 1 year ago

Unclear
Active Restake Users
Restake enabled count
Restake token Amount
Whale transactions (account, action, amount, to address, TX link)
Governance participation (№ proposal, account number votes, account token amount, validator amount votes, validator token amount, proposal status, Vote ration (account number votes/validator amount votes))
Amount of unique accounts participating in proposal, excluding accounts with < 0.01 Atom

Ales:
Fees Paid
Rich list (address, token amount, liquid tokens, staked tokens, Validator, Unbound tokens)
Unbound/stake/redelegations

**Comment by bro-n-bro-0** [comment]
@bro-n-bro-2 @iljagrabar14 
I think we have to decompose that issue 
Pics will help us to understand that issue better

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 
Please investigate:
circulating_supply API and community_pool

**Comment by bro-n-bro-0** [comment]
Whale transactions (account, action, amount, to address, TX link)
100,000 USD

**Comment by bro-n-bro-0** [comment]
Amount of unique accounts participating in the proposal

![telegram-cloud-photo-size-2-5312467356938783495-y](https://github.com/bro-n-bro/spacebox-api/assets/89854952/2d6f9193-bbde-4f79-acd3-6c11b9b456ee)

**Comment by bro-n-bro-0** [comment]
Fees Paid only native tokens for now

**Comment by bro-n-bro-0** [comment]
Unbound/stake/redelegations
regarded msgs for a time period

**Comment by bro-n-bro-2** [comment]
![image](https://github.com/bro-n-bro/spacebox-api/assets/89855562/5e8ee7a5-e2f3-493c-a5cf-def8a9c86a77)
Wealth Distribution
0-100
100-500
500-2000
2000-5000
5000-10000
10000-20000
20000-50000
50000-100000
100000-500000
500000+

**Comment by iljagrabar14** [comment]
> Unbound/stake/redelegations regarded msgs for a time period

from messages tables

**Comment by bro-n-bro-0** [comment]
- [ ] Total accounts
- [ ] Active accounts
- [ ] New accounts
- [ ] Inactive accounts
- [ ] Active Restake Users
- [ ] Restake enabled count
- [ ] Restake token Amount
- [ ] Gas Paid
- [ ] Fees Paid
- [ ] Total amount of transactions
- [ ] Top transactions per 30 days
- [ ] Rich list (address, token amount, liquid tokens, staked tokens, Validator, Unbound tokens)
- [ ] Whale transactions (account, action, amount, to address, TX link)
- [ ] Governance participation (№ proposal, account number votes, account token amount, validator amount votes, validator token amount, proposal status, Vote ration (account number votes/validator amount votes))
- [ ] Unbound/stake/redelegations
- [ ] Amount of unique accounts participating in proposal, excluding accounts with < 0.01 Atom
- [ ] Average stake (amount of accounts with less than 1k, 1k-5k, 5k-10k, > 10k)
- [ ] Vesting accounts

**Comment by iljagrabar14** [comment]
Active accounts 

by transaction table, historic data, count of unique users who made transaction

**Comment by bro-n-bro-0** [comment]
@iljagrabar14 
It's a bit mistake with data timeseries generation 
After grouping data like new accounts you may miss some dates if there're no new accounts on that day. But it have to be zero value
Please fix

**Comment by bro-n-bro-0** [comment]
@iljagrabar14 /statistics/transactions?from_date=2022-08-08&to_date=2023-08-08&detailing=day
the last value is 
```
    {
      "x": "2023-08-09",
      "y": 1261
    }
```
but the time range is 2023-08-08

**Comment by iljagrabar14** [comment]
> @iljagrabar14 /statistics/transactions?from_date=2022-08-08&to_date=2023-08-08&detailing=day the last value is
> 
> ```
>     {
>       "x": "2023-08-09",
>       "y": 1261
>     }
> ```
> 
> but the time range is 2023-08-08

fixed in https://github.com/bro-n-bro/spacebox-api/pull/74 to pprevent merge confilcts
