### ISSUE TITLE
Monitoring API Validator + (operator address)

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#63]
operator address
Logo + moniker
Voting power
Self bonded
Commission
Commission changes (min/max/per day)
Slashing count
Commission earned
Restake enabled
Unique delegators
New delegators (last 30 days)
Voting participation

**Comment by bro-n-bro-0** [comment]
Rewards earned as a separate endpoint. Distribution rewards table. Historical data + total earned for a period

**Comment by bro-n-bro-0** [comment]
Comission earned as a separate endpoint. Comission rewards table. Historical data + total earned for a period
