### ISSUE TITLE
Add active_restake_users API

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-api#81]
Try to find all turned-on restakes and calculate the number of restake users in a range

**Comment by bro-n-bro-0** [comment]
@iljagrabar14 take a look for this 

```sql=
SELECT day, count(*) FROM (
	SELECT arrayJoin(arrayMap(x -> toDateTime(x), range(toUInt64(toStartOfDay(start)), toUInt64(toStartOfDay(end)), 86400))) AS day, granter FROM (
		SELECT start, if(end_r != '1970-01-01', end_r, end) AS end, granter FROM (
			SELECT toDate(timestamp) AS start, toDate(expiration) AS end, granter  FROM (
				SELECT * FROM spacebox.grant_message FINAL
				WHERE msg_type = '/cosmos.staking.v1beta1.StakeAuthorization'
			) AS _t
			LEFT JOIN spacebox.block ON spacebox.block.height = _t.height
		) as grant
		LEFT JOIN (
			SELECT toDate(timestamp) as end_r, granter FROM (
				SELECT * FROM spacebox.revoke_message FINAL
				WHERE msg_type = '/cosmos.staking.v1beta1.MsgDelegate'
			) AS _t
			LEFT JOIN spacebox.block ON spacebox.block.height = _t.height
		) as revoke ON grant.granter = revoke.granter
	)
) AS _t
GROUP BY day
ORDER BY day
```

I've got all grant messages and decided grant activation start time as tx time, end as completion time
Then I joined revoke message and got the minimum date of both to understand the real grant activation range 
After that I distributed time range in a rows to understand the real amount of restake activated users

**Comment by bro-n-bro-0** [comment]
Also, I've made crosscheck validation like 
```sql=
SELECT count(*) 
FROM (
	SELECT * FROM spacebox.authz_grant FINAL
	WHERE msg_type = '/cosmos.staking.v1beta1.StakeAuthorization' AND expiration > now()
	ORDER BY expiration
) as _t
```
and values are equal

**Comment by bro-n-bro-0** [comment]
> @iljagrabar14 take a look for this
> 
> ```
> SELECT day, count(*) FROM (
> 	SELECT arrayJoin(arrayMap(x -> toDateTime(x), range(toUInt64(toStartOfDay(start)), toUInt64(toStartOfDay(end)), 86400))) AS day, granter FROM (
> 		SELECT start, if(end_r != '1970-01-01', end_r, end) AS end, granter FROM (
> 			SELECT toDate(timestamp) AS start, toDate(expiration) AS end, granter  FROM (
> 				SELECT * FROM spacebox.grant_message FINAL
> 				WHERE msg_type = '/cosmos.staking.v1beta1.StakeAuthorization'
> 			) AS _t
> 			LEFT JOIN spacebox.block ON spacebox.block.height = _t.height
> 		) as grant
> 		LEFT JOIN (
> 			SELECT toDate(timestamp) as end_r, granter FROM (
> 				SELECT * FROM spacebox.revoke_message FINAL
> 				WHERE msg_type = '/cosmos.staking.v1beta1.MsgDelegate'
> 			) AS _t
> 			LEFT JOIN spacebox.block ON spacebox.block.height = _t.height
> 		) as revoke ON grant.granter = revoke.granter
> 	)
> ) AS _t
> GROUP BY day
> ORDER BY day
> ```
> 
> I've got all grant messages and decided grant activation start time as tx time, end as completion time Then I joined revoke message and got the minimum date of both to understand the real grant activation range After that I distributed time range in a rows to understand the real amount of restake activated users

So, I think we can use that one
@iljagrabar14

**Comment by iljagrabar14** [comment]
can be done

**Comment by bro-n-bro-2** [comment]
Historical and static endpoints

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 issue with group by month: floating step

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 ready to check for everything except grouping by hour (timeout error)

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 actual added. close if it works
