### ISSUE TITLE
Add restake_token_amount

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-api#82]
The amount of restaked tokens in range by restake operators

**Comment by bro-n-bro-0** [comment]
Blocked by https://github.com/bro-n-bro/spacebox-crawler/issues/96

**Comment by bro-n-bro-0** [comment]
Here we are
```sql=
SELECT height, toUInt256OrZero(JSONExtractString(JSONExtractString(_t, 'amount'), 'amount'))  FROM (
	SELECT height, JSONExtractString(arrayJoin(JSONExtractArrayRaw(JSONExtractString(msgs)))) as _t FROM spacebox.exec_message FINAL
)
```

**Comment by iljagrabar14** [comment]
can implement

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 please check API 
/statistics/restake_token_amount

if it's ok, we can close issue

**Comment by bro-n-bro-2** [comment]
Please, add static endpoint as well.

**Comment by bro-n-bro-2** [comment]
Last day please.

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 @bro-n-bro-2 
please check both: historical and actual. if everything is ok, close issue please

**Comment by bro-n-bro-2** [comment]
@prevetal , please, proceed.
