### ISSUE TITLE
Add restake_enabled_count API 

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/spacebox-api#86]
As count of transaction execution

**Comment by bro-n-bro-0** [comment]
```sql=
SELECT timestamp, count FROM (
	SELECT height, count(*) AS count FROM spacebox.exec_message FINAL
	group by height 
) AS _t
LEFT JOIN spacebox.block ON spacebox.block.height = _t.height 
ORDER BY timestamp
```

So here we should define an amount of exec messages in a range

**Comment by iljagrabar14** [comment]
@bro-n-bro-0

**Comment by bro-n-bro-2** [comment]
Historical and static endpoints.

**Comment by bro-n-bro-0** [comment]
@iljagrabar14 it's alright, you can use it for API. Restake enabled means executions count, right? @bro-n-bro-2

**Comment by bro-n-bro-2** [comment]
@bro-n-bro-0 yes. and name it restake_execution_count

**Comment by iljagrabar14** [comment]
@bro-n-bro-2 ready to check

**Comment by bro-n-bro-2** [comment]
@prevetal please, proceeed.
