### ISSUE TITLE
Several Api fixes

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/spacebox-api#89]
Validator tab:
Endpoint - statistics/get_statistics_validators
- [x] Restake enabled (yes,no)
- [x] Validator Rank, according to voting power 
- [x] Return list of active set validators
- [x] Additional endpoint Commission Earned as static value
- [x] Add uptime stats. Static value for 10k blocks
- [x] ~~Add commission earned  as static~~ (moved to separated task, takes 2,5 min to calculate)
- [x] Add slashing as a number. If validator doesn't have slashes, set as 0. As for now, you don't send it as value. "slashing": 1,

Endpoint - /statistics/get_statistics_validators__operator_address_

- [ ] Voting participation. Currently we have number of proposals, in which  validator took a participation. We need also to show amount of proposals, in which validator could participate. Example: Last proposal is 150. Bro_n_Bro joined Cosmos Hub, when there were already 100 proposals passed, we couldn't participate in them, so we need to count proposals, that we can participate. So, there are should be returned votes such as 45/50.
**On pause. Will test with view tables**

- [x] Add uptime stats. Static value for 10k blocks and historical graph as all others (1 hour, day,week,month)
- [x]  Validator Rank, according to voting power 
- [x] Add validators website.
- [x] Voting power historical data
- [x] Unique delegators historical data
- [ ]  Add commission earned as static 
- [x]  Add commission earned as historical
- [x]  Restake enabled (yes,no)

New endpoint:
- [x] List of our delegators(wallets) with their balances. Input address to get staked amount, the similar as get_statistics_validators__operator_address_. Api should be able to accept array of addresses and return a sum of native tokens.

Endpoint - /statistics/get_statistics_inactive_accounts

- [x] #124

Endpoint -/statistics/get_statistics_total_accounts

- [x] Additional endpoint total_accounts as historical value

Endpoint - statistics/get_statistics_blocks_time

- [x] Additional endpoint get_statistics_blocks_time  as historical value

Account tab:
Add additional endpoint with static value.
- [x] /statistics/get_statistics_active_accounts
- [x] /statistics/get_statistics_new_accounts
- [x] /statistics/get_statistics_gas_paid
- [x] /statistics/get_statistics_transactions

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 
Additional endpoint inactive_accounts as historical value
Please provide sql

**Comment by iljagrabar14** [comment]
Restake enabled (yes,no)
spacebox.exec_message
msgs type message delegate -> delegator address
invalid json, must be fixed in DB before

**Comment by iljagrabar14** [comment]
Validator Rank, according to voting power
from 1 to n based on validator_voting_power

**Comment by iljagrabar14** [comment]
active validators
select * FROM spacebox.validator_status FINAL WHERE status = 3 and jailed = FALSE

**Comment by iljagrabar14** [comment]
validator created - select * FROM spacebox.create_validator_message cvm  
proposal created - select * FROM spacebox.proposal submit_type

**Comment by iljagrabar14** [comment]
select * FROM spacebox.validator_precommit vp for last 10000
count of each validator / 10000


for 500: return like true/false for each validator does he sign each block

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 
can't find a way to calculate proposals , that were created after validator was created. here is sql example, how i thought it could work

`select t.*,
(select count(*) from spacebox.proposal as p where p.submit_time > t.timestamp ) as value
from (
select * from spacebox.create_validator_message as cvm
left join (select * from spacebox.block) as b on cvm.height = b.height) as t`

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 
> Add uptime stats. Static value for 10k blocks
Don't really get it, looks like some validators appears more often then 1 time in each block, let's discuss

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 please help with it, any ideas?
 Unique delegators historical data

**Comment by iljagrabar14** [comment]
@bro-n-bro-0 
 Add commission earned as static

Timeout error
